version: "3.9"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: simpleorm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks: [devnet]

  server:
    build:
      context: .
      target: dev
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/simpleorm
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    command: npm run start:dev
    networks: [devnet]

volumes:
  pgdata:

networks:
  devnet:
    driver: bridge