FROM zhegal/node-base:latest AS builder
WORKDIR /app

COPY redis-like/package*.json ./
RUN npm install --omit=dev

COPY redis-like ./

FROM zhegal/node-base:latest
WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app ./

EXPOSE 4000
CMD ["node", "index.js"]