services:
  redis:
    build:
      context: .
      dockerfile: Dockerfile.redis
    image: redis:latest
    expose:
      - 4000
    networks:
      - internal

  kv:
    build:
      context: .
      dockerfile: Dockerfile.kv.dev
    image: kv:dev
    ports:
      - 8080:3000
    environment:
      - PORT=3000
      - REDIS_URL=http://redis:4000
    depends_on:
      - redis
    networks:
      - internal
    volumes:
      - ./kv-server:/app
      - /app/node_modules

networks:
  internal:
    driver: bridge